In [1]:
# grammar = CFG.fromstring("""
# S -> NP VP
# NP -> DT NN
# VP -> V NP
# DT -> 'the'
# NN -> 'boy' | 'ball'
# V -> 'kicked'
# """)


# parser = ChartParser(grammar)

# for tree in parser.parse(tokens):
#     print(tree)
#     tree.pretty_print()

In [2]:
# applications
# 1) sentiment analysis
# 2) chatbot
# 3) langauge translataion
# 4) word prediction
# 5) stock market prediction
# 6) weather forcasting
# 7) alexa /siri  Speech recognition
# 8) Text generation

In [4]:
# import numpy as np
# import pandas as pd
# from tensorflow.keras.layers import Dense,SimpleRNN
# from tensorflow.keras.models import Sequential

In [ ]:
# many to one

In [5]:
# X= np.array([[1,2,3,4]])
# y=np.array([5])

In [6]:
# input reshape

In [7]:
# CNN >> 1,256,256,3
# RNN >> 1,4,1

In [11]:
# X.shape

(1, 4)

In [8]:
# X_new=X.reshape((1,4,1))

In [9]:
# X_new

array([[[1],
        [2],
        [3],
        [4]]])

In [10]:
# y

array([5])

In [12]:
# model training

In [14]:
# model=Sequential([
#     SimpleRNN(10,activation='relu',input_shape=(4,1)),
#     Dense(1)
# ])

In [15]:
# model.compile(optimizer='adam',loss='mse')

In [22]:
# model.fit(X_new,y,epochs=400)

Epoch 1/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 7.3107
Epoch 2/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 7.1565
Epoch 3/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 7.0019
Epoch 4/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 6.8471
Epoch 5/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 6.6921
Epoch 6/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 6.5370
Epoch 7/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 6.3826
Epoch 8/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 6.2271
Epoch 9/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 6.0724
Epoch 10/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 5.9179
Epoch 11/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 5.7635
Epoch 12/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 5.6093
Epoch 13/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 5.4556
Epoch 14/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 5.3023
Epoch 15/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 5.1495
Epoch 16/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 4.9974
Epoch 17/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 4.8460
Epoch 18/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 4.6955
Epoch 19/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 4.5459
Epoch 20/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 4.3988
Epoch 21/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 4.2504
Epoch 22/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 4.1046
Epoch 23/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 3.9602
Epoch 24/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 3.8172
Epoch 25/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 3.6757
Epoch 26/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 3.5359
Epoch 27/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 3.3979
Epoch 28/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 3.2617
Epoch 29/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - loss: 3.1276
Epoch 30/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 2.9955
Epoch 31/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 2.8657
Epoch 32/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 2.7394
Epoch 33/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 2.6133
Epoch 34/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 2.4909
Epoch 35/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 2.3711
Epoch 36/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 2.2540
Epoch 37/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 2.1396
Epoch 38/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 2.0280
Epoch 39/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 1.9193
Epoch 40/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 1.8137
Epoch 41/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 1.7110
Epoch 42/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 1.6116
Epoch 43/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 1.5155
Epoch 44/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 1.4223
Epoch 45/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 1.3327
Epoch 46/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 1.2463
Epoch 47/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 1.1632
Epoch 48/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 1.0834
Epoch 49/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 1.0070
Epoch 50/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 0.9340
Epoch 51/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.8642
Epoch 52/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.7978
Epoch 53/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 0.7347
Epoch 54/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.6749
Epoch 55/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 0.6186
Epoch 56/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 0.5651
Epoch 57/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 0.5149
Epoch 58/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.4679
Epoch 59/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 0.4238
Epoch 60/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 0.3826
Epoch 61/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 0.3443
Epoch 62/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.3087
Epoch 63/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 0.2758
Epoch 64/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - loss: 0.2455
Epoch 65/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 0.2177
Epoch 66/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 0.1921
Epoch 67/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 0.1688
Epoch 68/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 0.1477
Epoch 69/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 0.1285
Epoch 70/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 0.1113
Epoch 71/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 0.0958
Epoch 72/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0820
Epoch 73/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 195ms/step - loss: 0.0697
Epoch 74/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 0.0588
Epoch 75/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 0.0493
Epoch 76/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0410
Epoch 77/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 0.0337
Epoch 78/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 0.0275
Epoch 79/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 0.0222
Epoch 80/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 0.0176
Epoch 81/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 0.0138
Epoch 82/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 0.0107
Epoch 83/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 0.0081
Epoch 84/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 0.0060
Epoch 85/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 0.0043
Epoch 86/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0030
Epoch 87/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 0.0020
Epoch 88/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 0.0012
Epoch 89/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 6.7479e-04
Epoch 90/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 3.2236e-04
Epoch 91/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 1.1270e-04
Epoch 92/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 1.5472e-05
Epoch 93/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 4.4925e-06
Epoch 94/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 5.7302e-05
Epoch 95/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 1.5496e-04
Epoch 96/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 2.8165e-04
Epoch 97/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 4.2443e-04
Epoch 98/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 5.7285e-04
Epoch 99/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 7.1876e-04
Epoch 100/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 8.5591e-04
Epoch 101/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 9.7978e-04
Epoch 102/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 0.0011
Epoch 103/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 0.0012
Epoch 104/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 0.0012
Epoch 105/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 0.0013
Epoch 106/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 0.0013
Epoch 107/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 0.0013
Epoch 108/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 0.0013
Epoch 109/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - loss: 0.0013
Epoch 110/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 0.0013
Epoch 111/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 0.0013
Epoch 112/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - loss: 0.0012
Epoch 113/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 0.0011
Epoch 114/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 0.0011
Epoch 115/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 0.0010
Epoch 116/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 9.4728e-04
Epoch 117/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 8.7634e-04
Epoch 118/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - loss: 8.0534e-04
Epoch 119/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 338ms/step - loss: 7.3524e-04
Epoch 120/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 6.6693e-04
Epoch 121/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 6.0104e-04
Epoch 122/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 5.3820e-04
Epoch 123/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 4.7874e-04
Epoch 124/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 4.2308e-04
Epoch 125/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - loss: 3.7139e-04
Epoch 126/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - loss: 3.2373e-04
Epoch 127/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 2.8016e-04
Epoch 128/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 2.4065e-04
Epoch 129/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 2.0510e-04
Epoch 130/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - loss: 1.7335e-04
Epoch 131/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 1.4522e-04
Epoch 132/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 1.2048e-04
Epoch 133/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 9.8930e-05
Epoch 134/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 8.0303e-05
Epoch 135/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step - loss: 6.4373e-05
Epoch 136/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 5.0859e-05
Epoch 137/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 3.9534e-05
Epoch 138/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 3.0149e-05
Epoch 139/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 2.2479e-05
Epoch 140/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 1.6316e-05
Epoch 141/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 1.1443e-05
Epoch 142/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 7.6885e-06
Epoch 143/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 4.8679e-06
Epoch 144/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 2.8317e-06
Epoch 145/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - loss: 1.4439e-06
Epoch 146/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 5.7990e-07
Epoch 147/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 1.2961e-07
Epoch 148/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 1.4552e-11
Epoch 149/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 1.0920e-07
Epoch 150/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 3.9020e-07
Epoch 151/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step - loss: 7.8240e-07
Epoch 152/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 1.2429e-06
Epoch 153/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 1.7295e-06
Epoch 154/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 2.2162e-06
Epoch 155/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 2.6781e-06
Epoch 156/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 3.0959e-06
Epoch 157/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 3.4584e-06
Epoch 158/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 3.7609e-06
Epoch 159/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 4.0013e-06
Epoch 160/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 4.1768e-06
Epoch 161/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 4.2867e-06
Epoch 162/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step - loss: 4.3362e-06
Epoch 163/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 4.3282e-06
Epoch 164/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 4.2709e-06
Epoch 165/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 4.1710e-06
Epoch 166/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 4.0300e-06
Epoch 167/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 3.8614e-06
Epoch 168/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 3.6671e-06
Epoch 169/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 3.4548e-06
Epoch 170/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 3.2248e-06
Epoch 171/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 2.9895e-06
Epoch 172/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - loss: 2.7504e-06
Epoch 173/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - loss: 2.5138e-06
Epoch 174/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 2.2834e-06
Epoch 175/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 2.0532e-06
Epoch 176/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 1.8352e-06
Epoch 177/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 1.6282e-06
Epoch 178/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 1.4336e-06
Epoch 179/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 1.2535e-06
Epoch 180/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 1.0875e-06
Epoch 181/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 9.3422e-07
Epoch 182/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 7.9680e-07
Epoch 183/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step - loss: 6.7188e-07
Epoch 184/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 5.6331e-07
Epoch 185/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 4.6626e-07
Epoch 186/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 3.8131e-07
Epoch 187/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 3.0860e-07
Epoch 188/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 2.4545e-07
Epoch 189/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 1.9245e-07
Epoch 190/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 1.4881e-07
Epoch 191/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 1.1141e-07
Epoch 192/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 8.1582e-08
Epoch 193/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 5.7986e-08
Epoch 194/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 3.9728e-08
Epoch 195/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 2.5517e-08
Epoch 196/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 1.5252e-08
Epoch 197/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 8.2082e-09
Epoch 198/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 3.4961e-09
Epoch 199/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 9.9044e-10
Epoch 200/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 3.2742e-11
Epoch 201/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 2.9468e-10
Epoch 202/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 1.4190e-09
Epoch 203/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step - loss: 3.1660e-09
Epoch 204/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 5.1843e-09
Epoch 205/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - loss: 7.4490e-09
Epoch 206/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 9.6488e-09
Epoch 207/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 1.1716e-08
Epoch 208/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 1.3760e-08
Epoch 209/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 1.5608e-08
Epoch 210/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 1.7070e-08
Epoch 211/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 1.8082e-08
Epoch 212/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 1.8859e-08
Epoch 213/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - loss: 1.9387e-08
Epoch 214/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 1.9520e-08
Epoch 215/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 1.9520e-08
Epoch 216/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 1.9122e-08
Epoch 217/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 1.8598e-08
Epoch 218/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 1.8082e-08
Epoch 219/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 1.7195e-08
Epoch 220/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 1.6209e-08
Epoch 221/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 1.5135e-08
Epoch 222/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 1.4097e-08
Epoch 223/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 1.2879e-08
Epoch 224/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step - loss: 1.1716e-08
Epoch 225/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 1.0608e-08
Epoch 226/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 9.5554e-09
Epoch 227/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 8.4694e-09
Epoch 228/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 7.4490e-09
Epoch 229/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 6.4940e-09
Epoch 230/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 5.6762e-09
Epoch 231/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 4.9133e-09
Epoch 232/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 4.2055e-09
Epoch 233/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 3.5527e-09
Epoch 234/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - loss: 3.0070e-09
Epoch 235/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 2.4593e-09
Epoch 236/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 1.9245e-09
Epoch 237/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 1.5664e-09
Epoch 238/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - loss: 1.2790e-09
Epoch 239/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 9.3132e-10
Epoch 240/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 7.1304e-10
Epoch 241/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 5.4592e-10
Epoch 242/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 3.8222e-10
Epoch 243/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - loss: 2.4761e-10
Epoch 244/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 1.5370e-10
Epoch 245/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 9.0949e-11
Epoch 246/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 5.1159e-11
Epoch 247/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 2.7512e-11
Epoch 248/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 8.1855e-12
Epoch 249/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 9.0949e-13
Epoch 250/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 2.2737e-13
Epoch 251/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 5.6843e-12
Epoch 252/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 1.4552e-11
Epoch 253/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 1.4552e-11
Epoch 254/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step - loss: 3.2742e-11
Epoch 255/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 3.8426e-11
Epoch 256/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 5.1159e-11
Epoch 257/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 5.8208e-11
Epoch 258/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 6.5711e-11
Epoch 259/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 7.3669e-11
Epoch 260/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 8.2082e-11
Epoch 261/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 7.3669e-11
Epoch 262/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 7.3669e-11
Epoch 263/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 7.3669e-11
Epoch 264/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - loss: 7.3669e-11
Epoch 265/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 7.3669e-11
Epoch 266/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - loss: 7.3669e-11
Epoch 267/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 7.3669e-11
Epoch 268/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 7.3669e-11
Epoch 269/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 8.2082e-11
Epoch 270/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 8.2082e-11
Epoch 271/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 8.2082e-11
Epoch 272/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 7.3669e-11
Epoch 273/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 6.5711e-11
Epoch 274/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 5.8208e-11
Epoch 275/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 5.8208e-11
Epoch 276/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 5.1159e-11
Epoch 277/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 4.4565e-11
Epoch 278/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 4.4565e-11
Epoch 279/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 3.8426e-11
Epoch 280/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - loss: 3.8426e-11
Epoch 281/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 3.8426e-11
Epoch 282/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 3.2742e-11
Epoch 283/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - loss: 3.2742e-11
Epoch 284/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - loss: 2.7512e-11
Epoch 285/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 2.2737e-11
Epoch 286/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 2.2737e-11
Epoch 287/400
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 2.2737e-11
Epoch 288/400

In [23]:
# model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

array([[4.9999986]], dtype=float32)

In [24]:
# a= np.array([[6,7,8,9]])

In [25]:
# a_new=a.reshape((1,4,1))

In [26]:
# model.predict(a_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step

array([[10.990681]], dtype=float32)

In [27]:
# case study 1 restaurant reviews predictions
# many to one
# LSTM/GRu

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('r_data.tsv',delimiter='\t')

In [3]:
df

                                                 Review  Liked
0                              Wow... Loved this place.      1
1                                    Crust is not good.      0
2             Not tasty and the texture was just nasty.      0
3     Stopped by during the late May bank holiday of...      1
4     The selection on the menu was great and so wer...      1
...                                                 ...    ...
1386                                                bad      0
1387                                           very bad      0
1388                                           bad food      0
1389                                          bad space      0
1390                                        bad service      0

[1391 rows x 2 columns]

In [4]:
df.shape

(1391, 2)

In [5]:
# data cleaning
df.isnull().sum()

Review    0
Liked     0
dtype: int64

In [6]:
df.dtypes

Review    object
Liked      int64
dtype: object

In [7]:
# ann/cnn >> 
# text ==input

In [8]:
df['Review']

0                                Wow... Loved this place.
1                                      Crust is not good.
2               Not tasty and the texture was just nasty.
3       Stopped by during the late May bank holiday of...
4       The selection on the menu was great and so wer...
                              ...
1386                                                  bad
1387                                             very bad
1388                                             bad food
1389                                            bad space
1390                                          bad service
Name: Review, Length: 1391, dtype: object

In [9]:
# Text proprocessing
#lowercase,special characters digit stopwords steming

In [10]:
# NLP >> nltk

In [11]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import re # regular Expression

In [12]:
s_list=stopwords.words('english')

In [13]:
s_list.remove('not')

In [14]:
len(s_list)

197

In [15]:
corpus=[]
for i in df['Review']:
    mystr=i.lower() # lowercase
    newstr= re.sub(r'[^A-Za-z\s]','',mystr)# remove special character and digit
    list1=word_tokenize(newstr) # tokenization
    list2=[ i for i in list1 if i not in s_list] # stopwords  remove
    ps=PorterStemmer()
    list3=[ps.stem(i) for i in list2] # stemming
    final=' ' .join(list3)
    corpus.append(final)

In [16]:
corpus

['wow love place',
 'crust not good',
 'not tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti didnt tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would not go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberrymmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place not worth time let alon vega',
 'not like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'that rightth red velvet cakeohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow',
 'found place accid could not happier',
 'seem like good quick place grab bite familiar pub food favor look elsewher',
 'overal like place lot',
 'redeem qualiti restaur inexpens',
 'ampl portion good price',
 'poor servic waiter made feel like stupid everi time came tabl',
 'first visit hiro delight',
 'servic suck',
 'shrimp tender moist',
 'not deal good enough would drag establish',
 'hard judg whether side good gross melt styrofoam didnt want eat fear get sick',
 'posit note server attent provid great servic',
 'frozen puck disgust worst peopl behind regist',
 'thing like prime rib dessert section',
 'bad food damn gener',
 'burger good beef cook right',
 'want sandwich go firehous',
 'side greek salad greek dress tasti pita hummu refresh',
 'order duck rare pink tender insid nice char outsid',
 'came run us realiz husband left sunglass tabl',
 'chow mein good',
 'horribl attitud toward custom talk one custom dont enjoy food',
 'portion huge',
 'love itfriendli server great food wonder imagin menu',
 'heart attack grill downtown vega absolut flatlin excus restaur',
 'not much seafood like string pasta bottom',
 'salad right amount sauc not power scallop perfectli cook',
 'rip banana not rip petrifi tasteless',
 'least think refil water struggl wave minut',
 'place receiv star appet',
 'cocktail handmad delici',
 'wed definit go back',
 'glad found place',
 'great food servic huge portion give militari discount',
 'alway great time do gringo',
 'updatew back second time still amaz',
 'got food appar never heard salt batter fish chewi',
 'great way finish great',
 'deal includ tast drink jeff went beyond expect',
 'realli realli good rice time',
 'servic meh',
 'took min get milkshak noth chocol milk',
 'guess known place would suck insid excalibur didnt use common sens',
 'scallop dish quit appal valu well',
 'time bad custom servic',
 'sweet potato fri good season well',
 'today second time ive lunch buffet pretti good',
 'much good food vega feel cheat wast eat opportun go rice compani',
 'come like experienc underwhelm relationship parti cant wait person ask break',
 'walk place smell like old greas trap other eat',
 'turkey roast beef bland',
 'place',
 'pan cake everyon rave tast like sugari disast tailor palat six year old',
 'love pho spring roll oh yummi tri',
 'poor batter meat ratio made chicken tender unsatisfi',
 'say food amaz',
 'omelet die',
 'everyth fresh delici',
 'summari larg disappoint dine experi',
 'like realli sexi parti mouth your outrag flirt hottest person parti',
 'never hard rock casino never ever step forward',
 'best breakfast buffet',
 'say bye bye tip ladi',
 'well never go',
 'back',
 'food arriv quickli',
 'not good',
 'side cafe serv realli good food',
 'server fantast found wife love roast garlic bone marrow ad extra meal anoth marrow go',
 'good thing waiter help kept bloddi mari come',
 'best buffet town price not beat',
 'love mussel cook wine reduct duck tender potato dish delici',
 'one better buffet',
 'went tigerlilli fantast afternoon',
 'food delici bartend attent person got great deal',
 'ambienc wonder music play',
 'go back next trip',
 'sooooo good',
 'real sushi lover let honest yama not good',
 'least min pass us order food arriv wasnt busi',
 'realli fantast thai restaur definit worth visit',
 'nice spici tender',
 'good price',
 'check',
 'pretti gross',
 'ive better atmospher',
 'kind hard mess steak',
 'although much like look sound place actual experi bit disappoint',
 'dont know place manag serv blandest food ever eaten prepar indian cuisin',
 'worst servic boot least worri',
 'servic fine waitress friendli',
 'guy steak steak love son steak best worst place said best steak he ever eaten',
 'thought youd ventur away get good sushi place realli hit spot night',
 'host staff lack better word bitch',
 'bland not like place number reason dont want wast time bad review ill leav',
 'phenomen food servic ambianc',
 'wouldnt return',
 'definit worth ventur strip pork belli return next time im vega',
 'place way overpr mediocr food',
 'penn vodka excel',
 'good select food includ massiv meatloaf sandwich crispi chicken wrap delish tuna melt tasti burger',
 'manag rude',
 'delici nyc bagel good select cream chees real lox caper even',
 'great subway fact good come everi subway not meet expect',
 'serious solid breakfast',
 'one best bar food vega',
 'extrem rude realli mani restaur would love dine weekend vega',
 'drink never empti made realli great menu suggest',
 'dont',
 'waiter wasnt help friendli rare check us',
 'husband ate lunch disappoint food servic',
 'red curri much bamboo shoot wasnt tasti',
 'nice blanket moz top feel like done cover subpar food',
 'bathroom clean place well decor',
 'menu alway chang food qualiti go servic extrem slow',
 'servic littl slow consid serv peopl server food come slow pace',
 'give thumb',
 'watch waiter pay lot attent tabl ignor us',
 'fianc came middl day greet seat right away',
 'great restaur mandalay bay',
 'wait forti five minut vain',
 'crostini came salad stale',
 'highlight great qualiti nigiri',
 'staff friendli joint alway clean',
 'differ cut piec day still wonder tender well well flavor',
 'order voodoo pasta first time id realli excel pasta sinc go gluten free sever year ago',
 'place good',
 'unfortun must hit bakeri leftov day everyth order stale',
 'came back today sinc reloc still not impress',
 'seat immedi',
 'menu divers reason price',
 'avoid cost',
 'restaur alway full never wait',
 'delici',
 'place handsdown one best place eat phoenix metro area',
 'dont go look good food',
 'ive never treat bad',
 'bacon hella salti',
 'also order spinach avocado salad ingredi sad dress liter zero tast',
 'realli vega fine dine use right menu hand ladi price list',
 'waitress friendli',
 'lordi khao soi dish not miss curri lover',
 'everyth menu terrif also thrill made amaz accommod vegetarian daughter',
 'perhap caught night judg review im not inspir go back',
 'servic leav lot desir',
 'atmospher modern hip maintain touch cozi',
 'not weekli haunt definit place come back everi',
 'liter sat minut one ask take order',
 'burger absolut flavor meat total bland burger overcook charcoal flavor',
 'also decid not send back waitress look like verg heart attack',
 'dress treat rude',
 'probabl dirt',
 'love place hit spot want someth healthi not lack quantiti flavor',
 'order lemon raspberri ice cocktail also incred',
 'food suck expect suck could imagin',
 'interest decor',
 'realli like crepe station',
 'also serv hot bread butter home made potato chip bacon bit topveri origin good',
 'watch prepar delici food',
 'egg roll fantast',
 'order arriv one gyro miss',
 'salad wing ice cream dessert left feel quit satisfi',
 'im not realli sure joey vote best hot dog valley reader phoenix magazin',
 'best place go tasti bowl pho',
 'live music friday total blow',
 'ive never insult felt disrespect',
 'friendli staff',
 'worth drive',
 'heard good thing place exceed everi hope could dream',
 'food great serivc',
 'warm beer didnt help',
 'great brunch spot',
 'servic friendli invit',
 'good lunch spot',
 'ive live sinc first last time ive step foot place',
 'worst experi ever',
 'must night place',
 'side delish mix mushroom yukon gold pure white corn beateou',
 'bug never show would given sure side wall bug climb kitchen',
 'minut wait salad realiz wasnt come time soon',
 'friend love salmon tartar',
 'wont go back',
 'extrem tasti',
 'waitress good though',
 'soggi not good',
 'jamaican mojito delici',
 'small not worth price',
 'food rich order accordingli',
 'shower area outsid rins not take full shower unless dont mind nude everyon see',
 'servic bit lack',
 'lobster bisqu bussel sprout risotto filet need salt pepperand cours none tabl',
 'hope bode go busi someon cook come',
 'either cold not enough flavor bad',
 'love bacon wrap date',
 'unbeliev bargain',
 'folk otto alway make us feel welcom special',
 'main also uninspir',
 'place first pho amaz',
 'wonder experi made place muststop whenev town',
 'food isnt bad enough enjoy deal world worstannoy drunk peopl',
 'fun chef',
 'order doubl cheeseburg got singl patti fall apart pictur upload yeah still suck',
 'great place coupl drink watch sport event wall cover tv',
 'possibl give zero star theyd',
 'descript said yum yum sauc anoth said eel sauc yet anoth said spici mayowel none roll sauc',
 'id say would hardest decis honestli ms dish tast suppos tast amaz',
 'not roll eye may stay not sure go back tri',
 'everyon attent provid excel custom servic',
 'horribl dont wast time money',
 'dish quit flavour',
 'time side restaur almost empti excus',
 'wasnt busi either also build freez cold',
 'like review said couldnt pay eat place',
 'drink took close minut come one point',
 'serious flavor delight folk',
 'much better ayc sushi place went vega',
 'light dark enough set mood',
 'base subpar servic receiv effort show gratitud busi wont go back',
 'owner realli great peopl',
 'noth privileg working',
 'greek dress creami flavor',
 'overal dont think would take parent place made similar complaint silent felt',
 'pizza good peanut sauc tasti',
 'tabl servic pretti fast',
 'fantast servic',
 'well wouldv given godfath zero star possibl',
 'know make',
 'tough short flavor',
 'hope place stick around',
 'bar vega not ever recal charg tap water',
 'restaur atmospher exquisit',
 'good servic clean inexpens boot',
 'seafood fresh gener portion',
 'plu buck',
 'servic not par either',
 'thu far visit twice food absolut delici time',
 'good year ago',
 'self proclaim coffe cafe wildli disappoint',
 'veggitarian platter world',
 'cant go wrong food',
 'cant beat',
 'stop place madison ironman friendli kind staff',
 'chef friendli good job',
 'ive better not dedic boba tea spot even jenni pho',
 'like patio servic outstand',
 'goat taco didnt skimp meat wow flavor',
 'think not',
 'mac salad pretti bland not get',
 'went bachi burger friend recommend not disappoint',
 'servic stink',
 'wait wait',
 'place not qualiti sushi not qualiti restaur',
 'would definit recommend wing well pizza',
 'great pizza salad',
 'thing went wrong burn saganaki',
 'wait hour breakfast could done time better home',
 'place amaz',
 'hate disagre fellow yelper husband disappoint place',
 'wait hour never got either pizza mani around us came later',
 'dont know slow',
 'staff great food delish incred beer select',
 'live neighborhood disappoint wont back conveni locat',
 'didnt know pull pork could soooo delici',
 'get incred fresh fish prepar care',
 'go gave star rate pleas know third time eat bachi burger write review',
 'love fact everyth menu worth',
 'never dine place',
 'food excel servic good',
 'good beer drink select good food select',
 'pleas stay away shrimp stir fri noodl',
 'potato chip order sad could probabl count mani chip box probabl around',
 'food realli bore',
 'good servicecheck',
 'greedi corpor never see anoth dime',
 'never ever go back',
 'much id like go back cant get pass atroci servic never return',
 'summer dine charm outdoor patio delight',
 'not expect good',
 'fantast food',
 'order toast english muffin came untoast',
 'food good',
 'never go back',
 'great food price high qualiti hous made',
 'bu boy hand rude',
 'point friend basic figur place joke didnt mind make publicli loudli known',
 'back good bbq lighter fare reason price tell public back old way',
 'consid two us left full happi cant go wrong',
 'bread made inhous',
 'downsid servic',
 'also fri without doubt worst fri ive ever',
 'servic except food good review',
 'coupl month later return amaz meal',
 'favorit place town shawarrrrrrma',
 'black eye pea sweet potato unreal',
 'wont disappoint',
 'could serv vinaigrett may make better overal dish still good',
 'go far mani place ive never seen restaur serv egg breakfast especi',
 'mom got home immedi got sick bite salad',
 'server not pleasant deal dont alway honor pizza hut coupon',
 'truli unbeliev good glad went back',
 'fantast servic pleas atmospher',
 'everyth gross',
 'love place',
 'great servic food',
 'first bathroom locat dirti seat cover not replenish plain yucki',
 'burger got gold standard burger kind disappoint',
 'omg food delicioso',
 'noth authent place',
 'spaghetti noth special whatsoev',
 'dish salmon best great',
 'veget fresh sauc feel like authent thai',
 'worth drive tucson',
 'select probabl worst ive seen vegasther none',
 'pretti good beer select',
 'place like chipotl better',
 'classywarm atmospher fun fresh appet succul steak basebal steak',
 'star brick oven bread app',
 'eaten multipl time time food delici',
 'sat anoth ten minut final gave left',
 'terribl',
 'everyon treat equal special',
 'shouldnt take min pancak egg',
 'delici',
 'good side staff genuin pleasant enthusiast real treat',
 'sadli gordon ramsey steak place shall sharpli avoid next trip vega',
 'alway even wonder food delici',
 'best fish ive ever life',
 'bathroom next door nice',
 'buffet small food offer bland',
 'outstand littl restaur best food ever tast',
 'pretti cool would say',
 'definit turn doubt ill back unless someon els buy',
 'server great job handl larg rowdi tabl',
 'find wast food despic wasnt food',
 'wife lobster bisqu soup lukewarm',
 'would come back sushi crave vega',
 'staff great ambianc great',
 'deserv star',
 'left stomach ach felt sick rest day',
 'drop ball',
 'dine space tini elegantli decor comfort',
 'custom order way youd like usual eggplant green bean stir fri love',
 'bean rice mediocr best',
 'best taco town far',
 'took back money got outta',
 'interest part town place amaz',
 'rude inconsider manag',
 'staff not friendli wait time serv horribl one even say hi first minut',
 'wont back',
 'great dinner',
 'servic outshin definit recommend halibut',
 'food terribl',
 'never ever go back told mani peopl happen',
 'dont recommend unless car break front starv',
 'come back everi time im vega',
 'place deserv one star food',
 'disgrac',
 'def come back bowl next time',
 'want healthi authent ethic food tri place',
 'continu come ladi night andddd date night highli recommend place anyon area',
 'sever time past experi alway great',
 'walk away stuf happi first vega buffet experi',
 'servic excel price pretti reason consid vega locat insid crystal shop mall aria',
 'summar food incred nay transcend noth bring joy quit like memori pneumat condiment dispens',
 'im probabl one peopl ever go ian not like',
 'kid pizza alway hit lot great side dish option kiddo',
 'servic perfect famili atmospher nice see',
 'cook perfect servic impecc',
 'one simpli disappoint',
 'overal disappoint qualiti food bouchon',
 'dont account know im get screw',
 'great place eat remind littl mom pop shop san francisco bay area',
 'today first tast buldogi gourmet hot dog tell ever thought possibl',
 'left frustrat',
 'ill definit soon',
 'food realli good got full petti fast',
 'servic fantast',
 'total wast time',
 'dont know kind best ice tea',
 'come hungri leav happi stuf',
 'servic give star',
 'assur wont disappoint',
 'take littl bad servic food suck',
 'gave tri eat crust teeth still sore',
 'complet gross',
 'realli enjoy eat',
 'first time go think quickli becom regular',
 'server nice even though look littl overwhelm need stay profession friendli end',
 'dinner companion told meeveryth fresh nice textur tast',
 'ground right next tabl larg smear beensteppedinandtrackedeverywher pile green bird poop',
 'furthermor cant even find hour oper websit',
 'weve tri like place time think done',
 'mistak',
 'complaint',
 'serious good pizza im expertconnisseur topic',
 'waiter jerk',
 'strike want rush',
 'nicest restaur owner ive ever come across',
 'never come',
 'love biscuit',
 'servic quick friendli',
 'order appet took minut pizza anoth minut',
 'absolutley fantast',
 'huge awkward lb piec cow th gristl fat',
 'definit come back',
 'like steiner dark feel like bar',
 'wow spici delici',
 'your not familiar check',
 'ill take busi dinner dollar elsewher',
 'id love go back',
 'anyway fs restaur wonder breakfastlunch',
 'noth special',
 'day week differ deal delici',
 'not mention combin pear almond bacon big winner',
 'not back',
 'sauc tasteless',
 'food delici spici enough sure ask spicier prefer way',
 'ribey steak cook perfectli great mesquit flavor',
 'dont think well go back anytim soon',
 'food gooodd',
 'far sushi connoisseur definit tell differ good food bad food certainli bad food',
 'insult',
 'last time lunch bad',
 'chicken wing contain driest chicken meat ever eaten',
 'food good enjoy everi mouth enjoy relax venu coupl small famili group etc',
 'nargil think great',
 'best tater tot southwest',
 'love place',
 'definit not worth paid',
 'vanilla ice cream creami smooth profiterol choux pastri fresh enough',
 'im az time new spot',
 'manag worst',
 'insid realli quit nice clean',
 'food outstand price reason',
 'dont think ill run back carli anytim soon food',
 'due fact took minut acknowledg anoth minut get foodand kept forget thing',
 'love margarita',
 'first vega buffet not disappoint',
 'good though',
 'one note ventil could use upgrad',
 'great pork sandwich',
 'dont wast time',
 'total letdown would much rather go camelback flower shop cartel coffe',
 'third chees friend burger cold',
 'enjoy pizza brunch',
 'steak well trim also perfectli cook',
 'group claim would handl us beauti',
 'love',
 'ask bill leav without eat didnt bring either',
 'place jewel la vega exactli ive hope find nearli ten year live',
 'seafood limit boil shrimp crab leg crab leg definit not tast fresh',
 'select food not best',
 'delici absolut back',
 'isnt small famili restaur fine dine establish',
 'toro tartar cavier extraordinari like thinli slice wagyu white truffl',
 'dont think back long time',
 'attach ga station rare good sign',
 'awesom',
 'back mani time soon',
 'menu much good stuff could not decid',
 'wors humili worker right front mebunch horribl name call',
 'conclus fill meal',
 'daili special alway hit group',
 'tragedi struck',
 'pancak also realli good pretti larg',
 'first crawfish experi delici',
 'monster chicken fri steak egg time favorit',
 'waitress sweet funni',
 'also tast mom multigrain pumpkin pancak pecan butter amaz fluffi delici',
 'id rather eat airlin food serious',
 'cant say enough good thing place',
 'ambianc incred',
 'waitress manag friendli',
 'would not recommend place',
 'overal wasnt impress noca',
 'gyro basic lettuc',
 'terribl servic',
 'thoroughli disappoint',
 'dont much pasta love homemad hand made pasta thin pizza',
 'give tri happi',
 'far best cheesecurd ever',
 'reason price also',
 'everyth perfect night',
 'food good typic bar food',
 'drive get',
 'first glanc love bakeri cafe nice ambianc clean friendli staff',
 'anyway not think go back',
 'point finger item menu order wont disappoint',
 'oh thing beauti restaur',
 'havent gone go',
 'greasi unhealthi meal',
 'first time might last',
 'burger amaz',

In [17]:
# corpus=[]
# for i in df['Review']:
#     mystr=i.lower()  # lowercase
#     newstr=re.sub(r'[^A-Za-z\s]','',mystr) # remove special chracters/digit
#     list1=word_tokenize(newstr) # tokenization
#     list2=[ i for i in list1 if i not in s_list]  # stopwords removal
#     ps=PorterStemmer()
#     list3=[ ps.stem(i)  for i in list2]  # stemming
#     final=' '.join(list3)
#     corpus.append(final)

In [18]:
# vectorization >> convert text data into numeric form

# 1) countvectorizar  >> Count word
# 2) Tokenizer(keras)
# 3) TF-ID vectorizer

In [19]:
# 1) countvectorizar  >> Count word >> unique word new column

#                    Hi    how are  you good   by tc
# Hi how are you     1     1    1    1   0     0  0 
# are you good       0     0    1    1    1    0  0
# by by tc           0     0    0    0    0    2  1

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus).toarray()
y=df['Liked']

In [21]:
X.shape

(1391, 1612)

In [22]:
# curse of dimensionality  >> model confuse

In [23]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1391, 1612))

In [24]:
cv.get_feature_names_out()

array(['absolut', 'absolutley', 'accid', ..., 'yum', 'yummi', 'zero'],
      shape=(1612,), dtype=object)

In [25]:
len(cv.get_feature_names_out())

1612

In [26]:
y

0       1
1       0
2       0
3       1
4       1
       ..
1386    0
1387    0
1388    0
1389    0
1390    0
Name: Liked, Length: 1391, dtype: int64

In [27]:
X_df=pd.DataFrame(X,columns=cv.get_feature_names_out())

In [28]:
X_df

,absolut,absolutley,accid,accommod,accomod,accordingli,account,ach,acknowledg,across,...,yelper,yet,youd,youll,your,yucki,yukon,yum,yummi,zero
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1386,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1387,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1388,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1389,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1390,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
# cross Validation

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_df,y,test_size=0.2,random_state=42)

In [31]:
# MODEL TRAINING
# Naive bays >> text data >> bayes therom >> cont ki probability count hoti hai
# >> CAlculate probabilyty of event
# multinomial >> text data

In [32]:
from sklearn.naive_bayes import MultinomialNB
clf= MultinomialNB()
clf.fit(X_train,y_train)

MultinomialNB()

In [33]:
clf.score(X_test,y_test)

0.8243727598566308

In [34]:
from sklearn.linear_model import LogisticRegression
clf1= LogisticRegression()
clf1.fit(X_train,y_train)

LogisticRegression()

In [35]:
clf1.score(X_test,y_test)

0.8172043010752689

In [36]:
# clf1 >> Logistic regression >> final

In [37]:
y_pred = clf1.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix,classification_report

In [39]:
print(confusion_matrix(y_test,y_pred))

[[108  23]
 [ 28 120]]

In [40]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.82      0.81       131
           1       0.84      0.81      0.82       148

    accuracy                           0.82       279
   macro avg       0.82      0.82      0.82       279
weighted avg       0.82      0.82      0.82       279

In [41]:
# new review

In [42]:
a='good taste'

In [43]:
a= np.array(['bad taste'])

In [44]:
a_new=cv.transform(a).toarray()

In [45]:
a_new

array([[0, 0, 0, ..., 0, 0, 0]], shape=(1, 1612))

In [46]:
clf1.predict(a_new)

d:\desktop\RNN\lstm_env\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [47]:
# solution >> RNN >> LSTM >> GRU
# next adv  >> transformer

In [48]:
# LSTM

In [49]:
# X=corpos
# y=df['liked']

In [50]:
df['Review']=corpus

In [51]:
df.head()

                                              Review  Liked
0                                     wow love place      1
1                                     crust not good      0
2                             not tasti textur nasti      0
3  stop late may bank holiday rick steve recommen...      1
4                            select menu great price      1

In [52]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [53]:
max_words = 5000
max_len = 100

In [54]:
tk= Tokenizer(num_words=max_words)
tk.fit_on_texts(df['Review'])

In [55]:
import pickle
with open('tokenizer.pkl','wb') as f:
    pickle.dump(tk,f)

In [56]:
X=tk.texts_to_sequences(df['Review'])

In [57]:
X = pad_sequences(X,maxlen=max_len)

In [58]:
X.shape

(1391, 100)

In [59]:
X
y=df['Liked']

In [60]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [61]:
# model training  >> LSTM

In [62]:
# Architecture of LSTM
# embedding layer
# LSTM layer
# Dropout layer(optional)
# Dense layer

In [63]:
# wow love place >> [123,516,78]
# LSTM cannot understand raw integers directly in a meaningful way.

# why embedding layer >> It converts each word ID into a dense vector representation.
#Captures semantic meaning meaning of words
#Similar words → similar vectors
# Learns during training

In [64]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

In [65]:
model=Sequential()
model.add(Embedding(input_dim=max_words,output_dim=128))  # unit >> 128
model.add(LSTM(128, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(1,activation='sigmoid'))

In [66]:
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [67]:
history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test)

)

Epoch 1/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 18s 213ms/step - accuracy: 0.5908 - loss: 0.6613 - val_accuracy: 0.6237 - val_loss: 0.6476
Epoch 2/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 203ms/step - accuracy: 0.7518 - loss: 0.5372 - val_accuracy: 0.7921 - val_loss: 0.4882
Epoch 3/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 179ms/step - accuracy: 0.9173 - loss: 0.2730 - val_accuracy: 0.8172 - val_loss: 0.4419
Epoch 4/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 203ms/step - accuracy: 0.9613 - loss: 0.1278 - val_accuracy: 0.7993 - val_loss: 0.5021
Epoch 5/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 192ms/step - accuracy: 0.9676 - loss: 0.1095 - val_accuracy: 0.8244 - val_loss: 0.4921
Epoch 6/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 183ms/step - accuracy: 0.9847 - loss: 0.0540 - val_accuracy: 0.8244 - val_loss: 0.5942
Epoch 7/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 179ms/step - accuracy: 0.9856 - loss: 0.0495 - val_accuracy: 0.8172 - val_loss: 0.6469
Epoch 8/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 179ms/step - accuracy: 0.9937 - loss: 0.0378 - val_accuracy: 0.8315 - val_loss: 0.6532
Epoch 9/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 164ms/step - accuracy: 0.9928 - loss: 0.0254 - val_accuracy: 0.8244 - val_loss: 0.7340
Epoch 10/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 11s 198ms/step - accuracy: 0.9937 - loss: 0.0251 - val_accuracy: 0.8244 - val_loss: 0.8137
Epoch 11/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 207ms/step - accuracy: 0.9955 - loss: 0.0194 - val_accuracy: 0.8280 - val_loss: 0.8830
Epoch 12/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 213ms/step - accuracy: 0.9946 - loss: 0.0154 - val_accuracy: 0.8351 - val_loss: 0.9501
Epoch 13/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 203ms/step - accuracy: 0.9955 - loss: 0.0134 - val_accuracy: 0.8244 - val_loss: 0.9464
Epoch 14/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 204ms/step - accuracy: 0.9973 - loss: 0.0143 - val_accuracy: 0.8315 - val_loss: 1.0245
Epoch 15/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 184ms/step - accuracy: 0.9955 - loss: 0.0169 - val_accuracy: 0.8280 - val_loss: 0.9090
Epoch 16/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 8s 229ms/step - accuracy: 0.9955 - loss: 0.0161 - val_accuracy: 0.8244 - val_loss: 0.9484
Epoch 17/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 167ms/step - accuracy: 0.9955 - loss: 0.0147 - val_accuracy: 0.8244 - val_loss: 0.9549
Epoch 18/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 6s 156ms/step - accuracy: 0.9973 - loss: 0.0116 - val_accuracy: 0.8244 - val_loss: 1.0507
Epoch 19/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 188ms/step - accuracy: 0.9955 - loss: 0.0123 - val_accuracy: 0.8315 - val_loss: 1.0263
Epoch 20/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 7s 189ms/step - accuracy: 0.9964 - loss: 0.0116 - val_accuracy: 0.8315 - val_loss: 1.0661

In [68]:
loss, accuracy = model.evaluate(X_test,y_test)
print('Test Accuracy',accuracy)

9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 68ms/step - accuracy: 0.8315 - loss: 1.0661
Test Accuracy 0.8315412402153015

In [69]:
model.save('lstm_reviews.keras')

In [70]:
y_pred=model.predict(X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 125ms/step

In [71]:
y_pred1=[ 1 if i>0.5 else 0 for i in y_pred]

In [72]:
from sklearn.metrics import confusion_matrix,classification_report

In [73]:
print(confusion_matrix(y_test,y_pred1))

[[111  20]
 [ 27 121]]

In [74]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.80      0.85      0.83       131
           1       0.86      0.82      0.84       148

    accuracy                           0.83       279
   macro avg       0.83      0.83      0.83       279
weighted avg       0.83      0.83      0.83       279

In [75]:
# new review

In [76]:
a= 'good taste'

In [77]:
def predict_text(text):
    text= text.lower()
    seq= tk.texts_to_sequences([text])
    padded = pad_sequences(seq,maxlen=max_len)
    pred=model.predict(padded)[0][0]

    if pred>0.5:
        return f"Positive({pred:.2f})"
    else:
        return f"Negative({pred:.2f})"

In [78]:
predict_text('not good taste')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step

'Negative(0.04)'

In [79]:
# not bad taste>> add i tsv file